use super::Atom;

use pyo3::prelude::*;

impl IntoPy<PyObject> for Atom {
    fn into_py(self, py: Python) -> PyObject {
        match self {
            Atom::H => "H" ,
            Atom::B => "B" ,
            Atom::C => "C" ,
            Atom::N => "N" ,
            Atom::O => "O" ,
            Atom::P => "P" ,
            Atom::S => "S" ,
            Atom::F => "F" ,
            Atom::Cl =>"Cl" ,
            Atom::Br =>"Br" ,
            Atom::I => "I" ,
            Atom::He =>"He" ,
            Atom::Li =>"Li" ,
            Atom::Be =>"Be" ,
            Atom::Ne =>"Ne" ,
            Atom::Na =>"Na" ,
            Atom::Mg =>"Mg" ,
            Atom::Al =>"Al" ,
            Atom::Si =>"Si" ,
            Atom::Ar =>"Ar" ,
            Atom::K => "K" ,
            Atom::Ca =>"Ca" ,
            Atom::Sc =>"Sc" ,
            Atom::Ti =>"Ti" ,
            Atom::V => "V" ,
            Atom::Cr =>"Cr" ,
            Atom::Mn =>"Mn" ,
            Atom::Fe =>"Fe" ,
            Atom::Co =>"Co" ,
            Atom::Ni =>"Ni" ,
            Atom::Cu =>"Cu" ,
            Atom::Zn =>"Zn" ,
            Atom::Ga =>"Ga" ,
            Atom::Ge =>"Ge" ,
            Atom::As =>"As" ,
            Atom::Se =>"Se" ,
            Atom::Kr =>"Kr" ,
            Atom::Rb =>"Rb" ,
            Atom::Sr =>"Sr" ,
            Atom::Y => "Y" ,
            Atom::Zr =>"Zr" ,
            Atom::Nb =>"Nb" ,
            Atom::Mo =>"Mo" ,
            Atom::Tc =>"Tc" ,
            Atom::Ru =>"Ru" ,
            Atom::Rh =>"Rh" ,
            Atom::Pd =>"Pd" ,
            Atom::Ag =>"Ag" ,
            Atom::Cd =>"Cd" ,
            Atom::In =>"In" ,
            Atom::Sn =>"Sn" ,
            Atom::Sb =>"Sb" ,
            Atom::Te =>"Te" ,
            Atom::Xe =>"Xe" ,
            Atom::Cs =>"Cs" ,
            Atom::Ba =>"Ba" ,
            Atom::La =>"La" ,
            Atom::Ce =>"Ce" ,
            Atom::Pr =>"Pr" ,
            Atom::Nd =>"Nd" ,
            Atom::Pm =>"Pm" ,
            Atom::Sm =>"Sm" ,
            Atom::Eu =>"Eu" ,
            Atom::Gd =>"Gd" ,
            Atom::Tb =>"Tb" ,
            Atom::Dy =>"Dy" ,
            Atom::Ho =>"Ho" ,
            Atom::Er =>"Er" ,
            Atom::Tm =>"Tm" ,
            Atom::Yb =>"Yb" ,
            Atom::Lu =>"Lu" ,
            Atom::Hf =>"Hf" ,
            Atom::Ta =>"Ta" ,
            Atom::W => "W" ,
            Atom::Re =>"Re" ,
            Atom::Os =>"Os" ,
            Atom::Ir =>"Ir" ,
            Atom::Pt =>"Pt" ,
            Atom::Au =>"Au" ,
            Atom::Hg =>"Hg" ,
            Atom::Tl =>"Tl" ,
            Atom::Pb =>"Pb" ,
            Atom::Bi =>"Bi" ,
            Atom::Po =>"Po" ,
            Atom::At =>"At" ,
            Atom::Rn =>"Rn" ,
            Atom::Fr =>"Fr" ,
            Atom::Ra =>"Ra" ,
            Atom::Ac =>"Ac" ,
            Atom::Th =>"Th" ,
            Atom::Pa =>"Pa" ,
            Atom::U => "U" ,
            Atom::Np =>"Np" ,
            Atom::Pu =>"Pu" ,
            Atom::Am =>"Am" ,
            Atom::Cm =>"Cm" ,
            Atom::Bk =>"Bk" ,
            Atom::Cf =>"Cf" ,
            Atom::Es =>"Es" ,
            Atom::Fm =>"Fm" ,
            Atom::Md =>"Md" ,
            Atom::No =>"No" ,
            Atom::Lr =>"Lr" ,
            Atom::Rf =>"Rf" ,
            Atom::Db =>"Db" ,
            Atom::Sg =>"Sg" ,
            Atom::Bh =>"Bh" ,
            Atom::Hs =>"Hs" ,
            Atom::Mt =>"Mt" ,
            Atom::Ds =>"Ds" ,
            Atom::Rg =>"Rg" ,
            Atom::Cn =>"Cn" ,
            Atom::Nh =>"Nh" ,
            Atom::Fl =>"Fl" ,
            Atom::Mc =>"Mc" ,
            Atom::Lv =>"Lv" ,
            Atom::Ts =>"Ts" ,
            Atom::Og =>"Og" ,
        }.into_py(py)
    }
}

impl<'source> FromPyObject<'source> for Atom {
    fn extract(obj: &'source PyAny) -> PyResult<Self> {
        let atom_str = <PyString as PyTryFrom>::try_from(obj)?.to_str()?;
        atom_str.parse::<Atom>().map_err(|_| PyValueError::new_err("Invalid str for Atom"))
            
    }
}
