[package]
name = "learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.4.1"
itertools = "0.10.3"
num-traits = "0.2.14"
ordered-float = { version = "2.10.0", features = ["serde"] }
petgraph = { version = "0.6.0", features = ["serde-1"] }
rand = "0.8.5"
rustc-hash = "1.1.0"
uuid = { version = "1.0", features = ["v4"] }
rayon = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
